
- name: Build Frontend
  block:
  - name: Remove frontend deploy directory, if already exists
    become: true
    file:
      path: "{{ frontend_deploy_path }}"
      state: absent

  - name: Create frontend deploy directory
    become: true
    file:
      path: "{{ frontend_deploy_path }}"
      state: directory
      owner: "{{ login_user }}"
      group: "{{ login_user }}"

  - name: Download latest frontend repository
    git:
      repo: "https://github.com/pxlsspace/pxls-web.git"
      dest: "{{ frontend_deploy_path }}"

  - name: Install node dependencies
    command: /usr/bin/npm install
    args:
      chdir: "{{ frontend_deploy_path }}"

  - name: Copy configuration reference
    copy:
      remote_src: true
      src: "{{ frontend_deploy_path }}/config.example.json5"
      dest: "{{ frontend_deploy_path }}/config.json5"

  - name: Frontend - Set Frontend Port
    ansible.builtin.replace :
      path: "{{frontend_deploy_path}}/config.json5"
      regexp: 'port: (\d*),$'
      replace: "port: {{ frontend_port }},"

  - name: Frontend - Set proxyTo value
    ansible.builtin.replace:
      path: "{{frontend_deploy_path}}/config.json5"
      regexp: "proxyTo: '(.*)',"
      replace: "proxyTo: '127.0.0.1:{{ server_port }}',"

  - name: Frontend - Set title value
    ansible.builtin.replace:
      path: "{{frontend_deploy_path}}/config.json5"
      regexp: "title: '(.*)',"
      replace: "title: '{{ public_hostname }}',"

  - name: Build frontend
    command: /usr/bin/npm run build
    args:
      chdir: "{{ frontend_deploy_path }}"