- name: Configure Database
  block:
  - name: Install psycopg2 package
    become: true
    apt:
      name: python3-psycopg2
      state: present

  - name: Create PostgreSQL user
    become: true
    become_user: postgres
    become_method: sudo
    ignore_errors: true
    command: |
      psql -c "CREATE USER {{ psql_username }} WITH ENCRYPTED PASSWORD '{{ psql_password }}'"
    args:
      chdir: "/tmp"
      
  - name: Create PostgreSQL database
    become: true
    become_user: postgres
    become_method: sudo
    ignore_errors: true
    command: |
      psql -c "CREATE DATABASE {{ psql_database }}"
    args:
      chdir: "/tmp"
      
  - name: Grant all privileges on the database to the user
    become: true
    become_user: postgres
    become_method: sudo
    ignore_errors: true
    command: |
      psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ psql_database }} TO {{ psql_username }};"
    args:
      chdir: "/tmp"