---
- name: Create pxls target directory
  become: yes
  file:
    path: "{{ pxls_deploy_path }}"
    state: directory
    owner: "{{ login_user }}"
    group: "{{ login_user }}"

- name: Copy production package to deploy path
  copy:
    remote_src: yes
    src: "{{ pxls_build_path }}/target/pxls-1.0-SNAPSHOT.jar"
    dest: "{{ pxls_deploy_path }}/pxls.jar"

- name: Copy configuration files
  template:
    src: "files/{{ item.src }}"
    dest: "{{ pxls_deploy_path }}/{{ item.dest }}"
  loop:
    - { src: 'pxls/pxls.conf', dest: 'pxls.conf' }
    - { src: 'pxls/palette.conf', dest: 'palette.conf' }
    - { src: 'pxls/roles.conf', dest: 'roles.conf' }

- name: Copy systemd files
  become: yes
  template:
    src: "files/systemd/{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
  loop:
    - { src: 'pxls-server.service', dest: 'pxls-server.service' }
    - { src: 'pxls-server.socket', dest: 'pxls-server.socket' }

- name: Pre-create storage path
  become: yes
  file:
    path: "{{ pxls_deploy_path }}/storage"
    state: directory
    owner: "{{ login_user }}"
    group: "{{ login_user }}"

- name: Copy pebble templates to deployment directory
  copy:
    remote_src: yes
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  loop:
    - { src: "{{ pxls_build_path }}/resources/public/pebble_templates/info.html", dst: "{{ pxls_deploy_path }}/storage/info.html" }
    - { src: "{{ pxls_build_path }}/resources/public/pebble_templates/faq.html", dst: "{{ pxls_deploy_path }}/storage/faq.html" }

- name: Enable systemd services
  become: true
  systemd:
    name: pxls-server.service
    state: started
    enabled: true