---
- name: Install OS prerequisites
  become: yes
  apt:
    name:
      - software-properties-common
      - ca-certificates
      - curl
      - gnupg
      - gettext
    state: present

- name: Create directory for apt keyrings
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Add Nodesource GPG key
  shell: |
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg
  become: yes

- name: Add Nodesource repository
  become: yes
  lineinfile:
    path: /etc/apt/sources.list.d/nodesource.list
    line: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
    create: yes

- name: Add PHP 7.x repository (needed for the admin panel)
  command: sudo add-apt-repository ppa:ondrej/php --yes
  become: yes

- name: Update APT package cache after adding repositories
  become: yes
  apt:
    update_cache: yes