---
- name: Set hostname to {{ public_hostname }}
  become: yes
  hostname:
    name: "{{ public_hostname }}"

- name: Update /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ public_hostname }} localhost"
    state: present